// <auto-generated />
using AssetInsight.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetInsight.Server.Migrations
{
    [DbContext(typeof(AssetInsightDBContext))]
    partial class AssetInsightDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.32");

            modelBuilder.Entity("AssetInsight.Server.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssestClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorDateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestorType")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalCommitment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Asset");
                });
#pragma warning restore 612, 618
        }
    }
}
